### PR TITLE
Adding myself to the table

### PR DESCRIPTION
**Pull request by markalbrand56**

### CODE REVIEW

**Review by sguthals — APPROVED** [review]
Nice! I only ever played one...and it wasn't really a racing game...Driver? From the like early 2000s? You just drove around a city and if you were speeding cops would chase you? I think there were other things you could do but I just drove around fake cities lol

Welcome!

**Comment by sguthals** [comment]
Welcome @markalbrand56 !

**Comment by markalbrand56** [comment]
> Nice! I only ever played one...and it wasn't really a racing game...Driver? From the like early 2000s? You just drove around a city and if you were speeding cops would chase you? I think there were other things you could do but I just drove around fake cities lol
> 
> Welcome!

Oh yeah, I think I remember that game haha. I actually don't remember the first racing game I ever played, but he first one I loved is Need For Speed Carbon, from 2006.

Thank you!

**Comment by sguthals** [comment]
O0o0o0 I've heard of Need For Speed, I should try it out! 

image

**Comment by markalbrand56** [comment]
Hahaha, it's an awesome game. I hope you like it!
image

**Pull request merged**
